// AUTO-GENERATED FILE. DO NOT EDIT.
const componentMap: Record<string, () => Promise<any>> = {
  "address": () => import("./address/address"),
  "city": () => import("./address/city"),
  "country": () => import("./address/country"),
  "state": () => import("./address/state"),
  "client": () => import("./basic/client"),
  "comments": () => import("./basic/comments"),
  "contact": () => import("./basic/contact"),
  "faqs": () => import("./basic/faqs"),
  "media": () => import("./basic/media"),
  "megamenu": () => import("./basic/megaMenu"),
  "menu": () => import("./basic/menu"),
  "pages": () => import("./basic/pages"),
  "permissions": () => import("./basic/permissions"),
  "roles": () => import("./basic/roles"),
  "submenu": () => import("./basic/submenu"),
  "testimonials": () => import("./basic/testimonials"),
  "users": () => import("./basic/users"),
  "author": () => import("./blog/author"),
  "blogmeta": () => import("./blog/blogmeta"),
  "blogs": () => import("./blog/blogs"),
  "bank-detail": () => import("./product/bank-detail"),
  "commission": () => import("./product/commission"),
  "vendor-commission": () => import("./product/vendor-commission"),
  "document": () => import("./product/document"),
  "product-brand": () => import("./product/product-brand"),
  "product-feature": () => import("./product/product-feature"),
  "product-ingridient": () => import("./product/product-ingridient"),
  "product-meta": () => import("./product/product-meta"),
  "product-specification": () => import("./product/product-specification"),
  "vendor": () => import("./product/vendor"),
  "meta": () => import("./seo/meta"),
};

export default componentMap;
